apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
    release: my-prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
      release: my-prom
  template:
    metadata:
      labels:
        app: sample-app
        release: my-prom
    spec:
      containers:
      - image: luxas/autoscale-demo:v0.1.2
        name: metrics-provider
        ports:
        - name: http
          containerPort: 8080
