apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
  {{- include "spring.labels" . | nindent 4}}
data:
  dbname: {{ .Values.configmap.database.dbname }}
  dbtable: {{ .Values.configmap.database.dbtable }}
  drink: {{ .Values.configmap.food.drink | upper }}
  eat: {{ .Values.configmap.food.eat | trunc 13 | quote }}
