apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.24.0
    ports:
    - containerPort: 80
  - name: springapp
    image: yanivomc/spring-music:latest
    ports:
    - containerPort: 8080
