
apiVersion: v1 
kind: Pod  
metadata: 
 name: nginx 
spec:
 containers: 
 - name: nginx 
   image: nginx:latest
   ports: 
   - containerPort: 80
 - name: springapp
   image: yanivomc/spring-music:latest
   ports: 
   - containerPort: 8080

---

apiVersion: v1 
kind: Pod  
metadata: 
 name: animals 
spec:
 containers: 
 - name: bear
   image: supergiantkir/animals:bear
   ports: 
   - containerPort: 80
 - name: moose
   image: supergiantkir/animals:moose
   ports: 
   - containerPort: 88888