apiVersion: batch/v1
kind: CronJob
metadata:
  name: ravid-hello-world
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-world
            image: alpine:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - echo "hello world"
          restartPolicy: OnFailure
